---

- name: Revoke role from database when reader
  become: true
  raw: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -d {{ databasename }} -c "REVOKE pg_read_all_data FROM {{ username }};"
  when: rolename | lower == 'read'

- name: Revoke additional role on database when writer
  become: true
  raw: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -d {{ databasename }} -c "REVOKE pg_read_all_data FROM {{ username }};"
  when: rolename | lower == 'read/write'
 
- name: Revoke additional role 2 on database when writer
  become: true
  raw: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -d {{ databasename }} -c "REVOKE USAGE, CREATE ON SCHEMA public FROM {{ username }};"
  when: rolename | lower == 'read/write'
 
- set_stats:
    data:
      db_roles:
        username: "{{ username }}"
        rolename: "{{ rolename }}"
        databasename: "{{ databasename }}"
        