---

- name: Get database list
  become: true
  shell: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -c "SELECT datname FROM pg_database WHERE datistemplate = false;"
  register: db_list

- name: Revoke roles from db_list from User
  become: true
  shell: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -d {{ item }} -c "REVOKE USAGE, CREATE ON SCHEMA public FROM {{ username }};"
  loop: "{{ db_list.stdout_lines[2:-1] }}" 

- name: Change owner from all db to postgres
  become: true
  shell: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -d {{ item }} -c "REASSIGN OWNED BY {{ username }} TO postgres;"
  loop: "{{ db_list.stdout_lines[2:-1] }}" 

- name: Drop Postgres User
  become: true
  raw: docker exec -it cloudbox-postgres psql -U {{ postgres_user }} -c "DROP USER {{ username }};"

- set_stats:
    data:
      db_users:
        username: "{{ username }}"
     