# - name: Download docker distrib
#   get_url:
#     url: "{{ distrib_store }}/{{ distrib_name }}/{{ distrib_version }}/{{ distrib_name }}.{{ archive_ext }}"
#     dest: "{{ docker_path }}/{{ distrib_name }}.{{ archive_ext }}"
#     username: "{{ gitea_user }}"
#     password: "{{ gitea_password }}"
#     validate_certs: false

# - name: Unarchive docker distrib
#   unarchive:
#     src: "{{ docker_path }}/{{ distrib_name }}.{{ archive_ext }}"
#     dest: "{{ docker_path }}/"
#     remote_src: yes

# - name: Install docker .deb packages
#   raw: "cd {{ docker_path }}/ && dpkg --force-confold -i containerd.io_*.deb \
#   docker-ce_*.deb \
#   docker-ce-cli_*.deb \
#   docker-buildx-plugin_*.deb \
#   docker-compose-plugin_*.deb"

#     - name: "Install systemd-timesyncd package"
#       apt:
#         name: docker
#         state: present
#       when: ansible_distribution.split(' ') | first | lower in ['ubuntu', 'debian']
#       ignore_errors: true

#     - name: "Install docker package for Astra"
#       block:
#         - name: "Install systemd-timesyncd using apt-get command for Astra"
#           command: apt-get install -y docker
#       when: ansible_distribution.split(' ') | first | lower in ['astra']
#       ignore_errors: true


# - name: "Install Docker for Ubuntu and Debian"
#   apt:
#     name:
#       - docker-ce
#       - containerd.io
#       - docker-ce-cli
#       - docker-buildx-plugin
#       - docker-compose-plugin
#     state: present
#   when: ansible_distribution.split(' ') | first | lower in ['ubuntu', 'debian']
#   ignore_errors: true

# - name: "Install Docker for Astra"
#   block:
#     - name: "Install Docker components using apt-get command for Astra"
#       command: apt-get install -y docker-ce containerd.io docker-ce-cli docker-buildx-plugin docker-compose-plugin
#   ignore_errors: true

- name: "Install Docker for Astra"
  block:
    - name: "Install Docker components using apt-get command"
      command: apt-get install -y --allow-unauthenticated docker-ce containerd.io docker-ce-cli docker-buildx-plugin docker-compose-plugin
  ignore_errors: true

