ansible_become: true
distrib_version: "1.0"


distrib_name: "{{ 'docker-distrib-ubuntu' if ansible_distribution.split(' ') | first | lower in ['ubuntu', 'astra', 'debian']
                  else 'docker-distrib-redos' if ansible_distribution.split(' ') | first | lower in ['red', 'centos']
                  else 'docker-distrib-almalinux' }}"


archive_ext: "tar.gz"
docker_path: "/tmp/docker-packages"